insert into public.exercises (owner_id, name, primary_muscle, equipment, is_unilateral) values
  (null, 'Barbell Bench Press',        'chest',      'barbell',    false),
  (null, 'Incline Dumbbell Press',     'chest',      'dumbbell',   false),
  (null, 'Cable Fly',                  'chest',      'cable',      false),
  (null, 'Push-up',                    'chest',      'bodyweight', false),
  (null, 'Overhead Press',             'shoulders',  'barbell',    false),
  (null, 'Dumbbell Lateral Raise',     'shoulders',  'dumbbell',   false),
  (null, 'Face Pull',                  'shoulders',  'cable',      false),
  (null, 'Triceps Pushdown',           'triceps',    'cable',      false),
  (null, 'Overhead Triceps Extension', 'triceps',    'dumbbell',   false),
  (null, 'Close-Grip Bench Press',     'triceps',    'barbell',    false),
  (null, 'Deadlift',                   'back',       'barbell',    false),
  (null, 'Barbell Row',                'back',       'barbell',    false),
  (null, 'Lat Pulldown',               'back',       'cable',      false),
  (null, 'Pull-up',                    'back',       'bodyweight', false),
  (null, 'Seated Cable Row',           'back',       'cable',      false),
  (null, 'Barbell Curl',               'biceps',     'barbell',    false),
  (null, 'Dumbbell Curl',              'biceps',     'dumbbell',   true),
  (null, 'Hammer Curl',                'biceps',     'dumbbell',   true),
  (null, 'Back Squat',                 'quads',      'barbell',    false),
  (null, 'Front Squat',                'quads',      'barbell',    false),
  (null, 'Leg Press',                  'quads',      'machine',    false),
  (null, 'Leg Extension',              'quads',      'machine',    false),
  (null, 'Bulgarian Split Squat',      'quads',      'dumbbell',   true),
  (null, 'Romanian Deadlift',          'hamstrings', 'barbell',    false),
  (null, 'Leg Curl',                   'hamstrings', 'machine',    false),
  (null, 'Hip Thrust',                 'glutes',     'barbell',    false),
  (null, 'Standing Calf Raise',        'calves',     'machine',    false),
  (null, 'Seated Calf Raise',          'calves',     'machine',    false),
  (null, 'Plank',                      'core',       'bodyweight', false),
  (null, 'Hanging Leg Raise',          'core',       'bodyweight', false),
  (null, 'Cable Crunch',               'core',       'cable',      false)
on conflict do nothing;